version: 2.1

jobs:
  spec:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - restore_cache:
          name: restore Gems
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: bundle install
          command: |
            bundle config set path 'vendor/bundle' && \
            bundle install
      - save_cache:
          name: save Gems
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle exec rspec

workflows:
  version: 2
  spec-workflow:
    jobs:
      - spec